name: Deploy Infra (Placeholder)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Terraform Init (Placeholder)
      run: echo "terraform init"

    - name: Terraform Apply (Placeholder)
      run: echo "terraform apply -auto-approve"

    - name: Deployment Success
      run: echo "Deployment simulated successfully"